### ISSUE TITLE
Two phase init requires noexcept, not constexpr

### ISSUE THREAD

**Issue by muggenhor** [ned14/outcome#136]
In [doc/tutorial/constructors/two-phase-init](https://github.com/ned14/outcome/blob/2470fc6eb728a6ce9aef97793f386d3db42c2439/doc/src/content/tutorial/constructors/two-phase-init.md) you are mentioning `constexpr` a lot while `noexcept` is what's necessary.

When you mention most objects and containers in the C++ standard library having `constexpr` constructors you're actually wrong, it's definitely `noexcept` there (and that only for default construction and moving, when the allocator supports it).

More generally however: for this strategy to be correct `constexpr` isn't a requirement (just nice to have), `noexcept` behaviour is.

**Comment by ned14** [comment]
The wording is poor in the tutorial. What was meant is that one should only do literal type operations in the first phase. Marking everything as `constexpr` is a useful discipline in this because the compiler will tell you when you are not doing a literal operation. I've already received a fair bit of feedback on exactly that page and topic, so I hope you don't mind if I close this issue - the poor wording will be fixed.

**Comment by muggenhor** [comment]
I don't mind that you close this, I only opened it to make sure you're aware of this.

Thanks for a really great library (great in impact, not in size :-).
