### ISSUE TITLE
Build builds tests by default

### ISSUE THREAD

**Issue by yurivict** [ned14/outcome#285]
It builds test/tests/core-outcome.cpp and many other tests.

By default it should build only the main library, and there should be a special option that enables tests.
This is because package builds don't need tests to be built to save CPU resources.

Could you please make all tests be conditional on a special cmake variable, like cmake's standard ```BUILD_TESTING```?

Thank you.

**Comment by BurningEnlightenment** [comment]
IIRC `PROJECT_IS_DEPENDENCY=ON` ought to disable the test suite. However, I also faintly remember something wrt this not working due to shadowing the cache value of said variable during quickcpplib bootstrapping... Have you looked at the vcpkg port config options?
https://github.com/microsoft/vcpkg/blob/a6657c38d506872a735f444159f31887791b07d3/ports/outcome/portfile.cmake#L42-L48

Furthermore, I consider that the buildsystem must be rewritten[¹](https://en.wikipedia.org/wiki/Carthago_delenda_est).

**Comment by ned14** [comment]
`BUILD_TESTING` is now respected. `PROJECT_DEPENDENCY` is now `${PROJECT_NAME}_DEPENDENCY`.
