### ISSUE TITLE
Deserialisation of result<int> does not compile

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#84]
In the docs ([here](http://ned14.github.io/outcome/reference/iostream_support/#standardese-outcome_v2_xxx::operator%3C%3C%3CR,S,P%3E(std::ostream&,result%3CR,S,P%3Econst&)))  we can see `operator<<` and `operator>>` for `result` but we cannot see its semantics. Does it output first some indicator of whether it stores a `T` or an `EC` and then the value, or something else?. If I serialize and then deserialize do I get the guarantee that I will get the same value back (regardless of the types)? Does `operator<<` also output the `spare_storage` part?

**Comment by ned14** [comment]
Fixed, let me know if the wording is okay.

**Comment by akrzemi1** [comment]
I get it now: for debugging use `print`, for marshaling use the operators. One question: do you want to commit to the particular format of operators (e.g. to using semicolon) or do you only want to give the guarantee that the state of `status` (including `spare_storage`) `T` and `EC` are preserved after marshaling?

Of course, the operators will only work when EC is an int-like type. It will not work for `EC` = `std::error_code` (see [https://wandbox.org/permlink/WiRBntlGlCEISLOn](https://wandbox.org/permlink/WiRBntlGlCEISLOn)), which is the default.

So the usage is rather marginal.

**Comment by ned14** [comment]
Heh, I can see the confusion regarding the semicolons. I'll fix that later today.

You're right that serialisation is only useful if EC or EP is not their default type. But completeness and all that.

**Comment by akrzemi1** [comment]
Now that I ave spent the night thinking about it. Given that:

- the goals you set for the library is for `result` only to be returned from functions (rather than being stored and passed around),
- that most of the things cannot be deserialized correctly (`storage_part` is like pointer: the same numeric value will not work when the object is reconsructed),

I believe that the best approach would be not to provide the interface for marshaling at all. Only leave the interface for debug-printing. (Maybe use `operator<<` (and no `operator>>`) for debug printing, as `std::thread::id` does. 

Do any of the production use cases of `outcome` use this serialization facility?

**Comment by ned14** [comment]
It was, and still is, my intention for KernelTest to write outcomes to a database. And I figured if I had a use case for that, so would somebody else.

But you're right that marshalling is incomplete because `exception_ptr` can't be marshalled. Fixing that was one of those "todo" things, and until then I have it static asserting to prevent usage.

In terms of whether marshalling at all or not, it seems to me that there is no harm in the present approach. Can you think of any danger in providing marshalling?

**Comment by akrzemi1** [comment]
No danger. It is just confusion. By providing those members you give false expectation that you can serialize and deserialize a `result`. Now when deserialization of `result<int>` does not even compile, it is perceived as a bug.

> It was, and still is, my intention for KernelTest to write outcomes to a database

*Only* to write? Or also to read back? If the latter how do you intend to deal with the fact that `result<int>` cannot be deserialized?

**Comment by ned14** [comment]
> Now when deserialization of result<int> does not even compile, it is perceived as a bug.

It doesn't compile? I didn't know that. That changes things. I'll change the title of this issue accordingly.

**Comment by ned14** [comment]
Now trapped and prevented by static_assert, same as with outcome. Thanks for the bug report!

**Comment by akrzemi1** [comment]
Trapped what? `operator<<` for serializing?

**Comment by ned14** [comment]
It's a placeholder really, so I'm static asserting the most common use with a helpful message. At some future point I'll implement something which does serialise and deserialise error_code and exception_ptr so KernelTest can read and write them to/from a database. You are right that otherwise, if the types involved do not implement operator << or >>, there is no requires machinery to disable the Outcome editions.

Now I think about that, I think I ought to add that, so I will.
