### ISSUE TITLE
`OUTCOME_TRY` or `BOOST_OUTCOME_TRY`?

### ISSUE THREAD

**Issue by akrzemi1** [ned14/outcome#97]
So, now we are reviewing a "stand-alone" library, which uses macro names like `OUTCOME_TRY`. During Boost review we will expect that names adhere to Boost standards, so for instance macro names start with `BOOST_`. Will we be provided with a different version of library and documentation that adheres to Boost standards? Are such docs available right now somewhere?

**Comment by ned14** [comment]
You mean https://github.com/ned14/boost-outcome? I will port over the missing unit tests early next week, but it's running the full test suite otherwise on the Boost-ified edition.

It's Boost-ready, apart from the docs, and as I said to Vicente we cannot put those into Boost format until we decide how to do that, and that's a decision I cannot alone take as it requires lots of other people to say what's allowed and/or possible.

**Comment by akrzemi1** [comment]
So, if I understood correctly, you expect of Boost review that people evaluate (apart from design and implementation of the library) the intellectual content of the docs but not the format or technology of the docs, because the latter will be different but you do not know what it will be. There is only your commitment that it will be something compliant with Boost policy. Is that right?

**Comment by ned14** [comment]
People just need to perform the following when reading the docs:

- `OUTCOME_*` => `BOOST_OUTCOME_*`
- `outcome::v2_xxx` => `boost::outcome::v2_xxx`
- `Outcome` => `Boost.Outcome`

... and so on.

I don't think it'll be an issue personally, but we shall see how things go. This situation is simply because I don't know how keen the boost-website maintainers and release managers will be on installing a whole new set of tooling just for Outcome. If not, we'll send them prebuilt HTML docs. If on the other they are keen, we'll need to configure some cronjobs on the Boost servers. There is also the possibility that the reviewers dislike the docs enough that they make acceptance conditional on a complete replacement.

It's very hard to say right now, so rather than waste effort on mocking up Boost format docs, I'm going to rely on the community to perform some search and replace. This is my third review, I have confidence in them on this.

**Comment by akrzemi1** [comment]
In that case I would recommend to make it very clear in the Boost review announcement:

- The "intellectual" content of the docs is fixed,
- You commit to applying Boost name adjustments if library is accepted,
- You commit to porting the docs to HTML or QBK if this is the verdict of the review.
